### ISSUE TITLE
Path to requirements.txt doesn't resolve

### ISSUE THREAD

**Issue by mmaz2301** [Lucas-C/pre-commit-hooks-safety#10]
When I run 
michael:outbound-file-transfer$ safety check -r requirements.txt
safety works.  When I use the pre-commit hook configuration:

 repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
    - 
I get 

safety...............................................(no files to check)Skipped

**Comment by Lucas-C** [comment]
`pre-commit` hooks are only executed when corresponding files have been modified in the commit.
If you did not introduce any change on your `requirements.txt` files in your commit, this hook won't be executed.

You can call the `pre-commit` CLI manually in order to trigger hooks execution.
For example, to execute all hooks:

    pre-commit run --all-files

**Comment by mmaz2301** [comment]
Thanks!  Appreciate your help!

**Comment by Lucas-C** [comment]
Glad it helped you :)
Closing this issue then, feel free to open another one if you face other problems
