### ISSUE TITLE
update hardcoded path to poetry executable

### ISSUE THREAD

**Issue by Cielquan** [Lucas-C/pre-commit-hooks-safety#20]
> The get-poetry.py script described here will be replaced in Poetry 1.2 by install-poetry.py. From Poetry 1.1.7 onwards, you can already use this script as described here.

The new script installs poetry to another place:

> $HOME/.local/bin for Unix
> %APPDATA%\Python\Scripts on Windows

Source: https://python-poetry.org/docs/master/#installing-with-the-official-installer

**Comment by Lucas-C** [comment]
Thank you for the heads-up!

`pre-commit-hooks-safety` looks for `poetry` in the `$PATH`,
so I'm not sure there is any need for a fix here...
https://github.com/Lucas-C/pre-commit-hooks-safety/blob/master/pre_commit_hooks/safety_check.py#L68

@Cielquan: have you got any issue yourself with `pre-commit-hooks-safety` due to this?
If so, what was the error?

I have just made a test of using `install-poetry.py` in the Actions pipeline, and the current hook tests all pass fine:
https://github.com/Lucas-C/pre-commit-hooks-safety/runs/4912559173

**Comment by Cielquan** [comment]
No I do not have any issues.

I just looked at the code to understand how you grab the dependencies from poetry and there I saw an else block which is hardcoded to the <1.2 path: https://github.com/Lucas-C/pre-commit-hooks-safety/blob/master/pre_commit_hooks/safety_check.py#L70

**Comment by Lucas-C** [comment]
Indeed. And I think I prefer to keep it, for better compatibility with people that still have `poetry` installed there.

I'm going to add `.local/bin` too, but I'm not sure that's really needed.
